#!/usr/bin/php
<?php
declare(strict_types=1);

use App\Core\Container;

require __DIR__ . '/../../vendor/autoload.php';

const COMPANIES = [
    ['title' => 'Победа', 'code' => 'Pobeda', 'file' => 'pobeda.json'],
    ['title' => 'Smartavia', 'code' => 'SmartAvia', 'file' => 'smartavia.json'],
];

function createCompany(array $company): void
{
    Container::pdo()
        ->prepare('INSERT INTO companies (title, code) VALUES (?, ?)')
        ->execute([$company['title'], $company['code']]);
}

function createAirport(array $airport): void
{
    Container::pdo()
        ->prepare('INSERT INTO airports (code, city_code, sort, title) VALUES (:iataCode, :metropolitanCode, :sort, :name)')
        ->execute($airport);
}

function attachCompanyToAirport(string $companyCode, string $airportCode): void
{
    Container::pdo()
        ->prepare('INSERT INTO airport_company (airport_code, company_code) VALUES (?, ?)')
        ->execute([$airportCode, $companyCode]);
}

function getAirports(string $file): array
{
    return json_decode(
        file_get_contents(__DIR__ . "/data/airports/$file"),
        true
    );
}

$pdo = Container::pdo();
$pdo->beginTransaction();
$airports = [];
foreach (COMPANIES as $company) {
    createCompany($company);
    $companyAirports = getAirports($company['file']);
    foreach ($companyAirports as $airport) {
        if (empty($airports[$airport['iataCode']])) {
            createAirport($airport);
            $airports[$airport['iataCode']] = true;
        }
        attachCompanyToAirport($company['code'], $airport['iataCode']);
    }
}
$pdo->commit();
